name: Android CI

on:
  push: # quando de um push executa esse script
    branches: [ "master" ] # branch master

jobs:
  build:
    runs-on: ubuntu-latest # versao da maquina virtual

    steps: # passo
      - uses: actions/checkout@v4
      - name: set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build