on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v2
        id: release
        with:
          release-type: simple
#           - uses: actions/checkout@v4
#           - name: tag major and minor versions
#          command: manifest
#          token: ${{secrets.SENHA_GITHUB_2}}
#          default-branch: master
