name: release-please

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ github.token }}

  upload-artifact:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Create Connector Jar
        run: ./gradlew shadowJar

      - name: Upload Release Artifact